---
title: "Git and Github"
subtitle: "Workshop Exercises"
author: 'Tim Beissinger, Elizabeth King, and Kevin Middleton'
date: 'Last updated: `r Sys.Date()`'
output:
  ioslides_presentation:
    fig_width: 7
    css: styles.css
---

```{r setup, echo=FALSE}
```

## Notes

This workshop was modeled from several tutorials available online and in some cases, took material and quotes directly:

[Git for Humans by Alice Bartlett](https://speakerdeck.com/alicebartlett/git-for-humans)

[Happy Git and Github for the useR by Jenny Bryan](http://happygitwithr.com/)

[git/github guide by Karl Broman](http://kbroman.org/github_tutorial/)

[Version Control with Git from Software Carpentry](http://swcarpentry.github.io/git-novice/)

A Git and Github cheatsheet is [here](https://services.github.com/on-demand/downloads/github-git-cheat-sheet.pdf)

Additional Git resources are listed in Karl's guide: [Resources](http://kbroman.org/github_tutorial/pages/resources.html)

## Ways to use Git

There are a few ways to use Git. We will show you all three today. 

- via the command line 
- via a desktop GitHub client
    - [GitKraken](https://www.gitkraken.com/)
    - [GitHub Desktop](https://desktop.github.com/)
- via Rstudio (using [RStudio projects](https://support.rstudio.com/hc/en-us/articles/200526207-Using-Projects))

## Plan for the day

We will use two major examples today to learn about using git:
1. Setting up a personal miscellaneous R functions repository
1. Setting up a collaborative repository with a small group

Our goal at the end of the day is for you to feel comfortable using git and committed to use git for the projects you are working on now and in the future.

## Starting a project (repository)

The first thing we need to do is start a new repository. There are a couple different ways to set up a repository. 

1. Starting a repository on GitHub (this is the preferred method)
1. Starting a repository on your machine
    - beginning with an empty project folder
    - beginning with a project folder with stuff in it

> How do you decide what defines a repository?
    
## Starting a repository remotely on GitHub

**Activity**

1. Log in to GitHub.com 
1. Click the "New Repository" button (under the `+` icon in the menu bar)
1. Name your repository with your initials and misc (for example EGKmisc) to hold your miscellaneous R functions
1. Clone the repository to your local machine
  - command is git clone

## Benefits of starting a repository on GitHub

- Local copy automatically set to properly interact with github
    - Push and pull
- Move local files into empty repository
    - Commit in batch or individually



## Ignoring files with `.gitignore`

  - git will track all the files in your repository unless you tell it otherwise
  - common files you may not want to track include very large data files and files like the R history file
  .DS_Store
.Rhistory
.RData

## Make a change

**Activity**
1. Start a new R script
1. Write a function or copy over a function you've written before
1. Save your file with an informative name in your project folder

- Take a look at what you've done by typing git status or git diff

## Commits

When you are happy with some work you've done and want to take a snapshot, you will do what is called a commit.

**Activity**
1. Stage your files
1. Commit them with a message like "add cool function"


## Syncing: Push and Pull

What we've done so far is take a snapshot locally on our machine. To copy that over to the remote repository on github, we need to push our changes. When we are collaborating, we will also need to pull others changes from the remote. We'll get to this in a bit.

**Activity**
1. git push

## Git Clients

So far, we've used the command line to use git. There are more user friendly mechanisms - git clients.

Let's go through the same steps with a client.

## GitKraken



## Starting a repository locally


    - Start locally (with & without stuff)
## RStudio Projects

## Problems, warnings, how to recover

Where do problems come from
Burn down
## Typical use

  1. Do some work on your project
  1. 

## Distributing code: making things reproducible for others

## Collaborating with others
